name       : tuxpaint-stamps
version    : 2014.08.23
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/tuxpaint/tuxpaint-stamps/2014-08-23/tuxpaint-stamps-2014.08.23.tar.gz : d8005d57b08f18b54df5a1baf86f09268278d1252de6b193119713f265e61466
license    : GPL-2.0
component  : games.learning
summary    : Additional stamps for Tux Paint
description: |
    Additional stamps for Tux Paint
rundeps    :
    - tuxpaint
build      : |
    %make
install    : |
    %make DATA_PREFIX=$installdir/usr/share/tuxpaint/ install-all
