name       : tuxpaint-stamps
version    : 2018.08.01
release    : 2
source     :
    - https://sourceforge.net/projects/tuxpaint/files/tuxpaint-stamps/2018-09-01/tuxpaint-stamps-2018.09.01.tar.gz/download : d78f55e7fde6abc3fb1a79e6fed0114a2c0ad2edff7ee5f8db43fa23e61079ea
license    : GPL-2.0-or-later
component  : games.learning
summary    : Additional stamps for Tux Paint
description: |
    Additional stamps for Tux Paint
rundeps    :
    - tuxpaint
build      : |
    %make
install    : |
    %make DATA_PREFIX=$installdir/usr/share/tuxpaint/ install-all
